
# .github/workflows/lint.yml

name: Lint # name of the action (displayed in the github interface)

on: [push, pull_request]

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
  
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Code Linting
        run: npm run lint
        env:
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
